### ISSUE TITLE
[DOC] Add types of tests to documentation for Certification v1

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-certification#21]
Need to add types to https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md#cnf-certification-list-of-tests---v10-beta

Sample text to add:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/14348948/175576082-af394fd7-6db7-46db-a947-58f4829768d9.png">

**Comment by lixuna** [comment]
This effort has been completed in #22 

New issue will be created for future enhancements 

![Screen Shot 2022-10-05 at 10 50 10 AM](https://user-images.githubusercontent.com/11701267/194105028-3de810cf-dc62-4894-9e3a-035b82761bbc.png)
