### ISSUE TITLE
[Documentation] remove network_policies from list of tests for next release of cert

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-certification#23]
Description: 
- `network_policies` test is a bonus test for CNFCertification-1.0-beta.md
- `network_policies` test was removed from the testsuite in v0.30.1
- `network_policies` test will not be included in the next release of CNFCertification
- remove `network_policies` test from next version of CNF Certification List of Tests - v1.0.x

Current location of documentation:
- https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md#network-policies

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-certification/pull/49

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md#network-policies, I do not see `network_policies` in the list of tests.

**Comment by lixuna** [comment]
What I would expect to see:
- 'network_policies' remains in the list of tests for [CNFCertification-1.0-beta.md#network-policies](https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md#network-policies),
- 'network_policies' is not listed in the new 1.1-beta.md file (see #38 )

**Comment by lixuna** [comment]
**Acceptance Criteria**

- [x]  When I view https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.1-beta.md, I do not see network_policies in the list of tests.
