### ISSUE TITLE
[Documentation] remove dangerous_capabilities from list of tests for next release of cert

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-certification#24]
Description: 
- `dangerous_capabilities` test is a normal test for CNFCertification-1.0-beta.md
- `dangerous_capabilities` test was removed from the testsuite in v0.30.1
- `dangerous_capabilities` test will not be included in the next release of CNFCertification
- remove `dangerous_capabilities` test from next version of CNF Certification List of Tests - v1.0.x

Current location of documentation:
- https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md#dangerous-capabilities

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-certification/pull/49

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When I view https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md#network-policies, I do not see `dangerous_capabilities` in the list of tests.

**Comment by lixuna** [comment]
Acceptance Criteria

- [x] When I view https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.1-beta.md, I do not see dangerous_capabilities in the list of tests.
