### ISSUE TITLE
PSI Bridge now supports only 1 webcam

### ISSUE THREAD

**Issue by Ravishanker74** [cncf/cnf-certification#28]
PSI Bridge now supports only 1 webcam which ever is used for the initial secure browser has to be used for the complete exam. The implication of this for candidates giving the certification exam on desktop systems is the wired USB camera should be able to show the ID card for verification purposes clearly. It is not possible to switch to desktop fixed camera for validating the ID and then to USB wired camera to show the exam room. The exam pre-flight check only measures the resolution of the camera and not its focus. Most USB webcams are having fixed focus have no option to adjust focus when showing ID cards. The name of the candidate has to be clearly visible for exam proctor to release the exam. This pre-check has to be done manually as of now.

**Comment by taylor** [comment]
@Ravishanker74 no camera is required.  Closing as n/a.
