### ISSUE TITLE
[Documentation] create an updated screenshot for testing feedback

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-certification#31]
What we have now: 

![Screen Shot 2022-08-25 at 12 18 31 PM](https://user-images.githubusercontent.com/11701267/186729131-d7bc2c64-8c3d-4353-9ed3-5483d3878dc8.png)

**Comment by agentpoyo** [comment]
Currently blocked by this new bug: https://github.com/cncf/cnf-testsuite/issues/1683

**Comment by agentpoyo** [comment]
<img width="652" alt="cnf-testsuite_console" src="https://user-images.githubusercontent.com/14348948/195431272-04c4a10f-b4f6-40af-ba23-ba8676473bf2.png">

**Comment by lixuna** [comment]
Looks good! Thank you for updating the slide deck, @agentpoyo
