### ISSUE TITLE
[Documentation] create an updated screenshot for test Results YAML w/ Summary

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-certification#32]
What we have now: 

![Screen Shot 2022-08-25 at 12 19 29 PM](https://user-images.githubusercontent.com/11701267/186729319-91acc813-154d-4b76-8079-14d3258e9518.png)

**Comment by agentpoyo** [comment]
Currently blocked by this new bug: https://github.com/cncf/cnf-testsuite/issues/1683

**Comment by agentpoyo** [comment]
<img width="386" alt="results" src="https://user-images.githubusercontent.com/14348948/195431594-808657ba-6de9-4509-bb48-332dac4fb1e7.png">

**Comment by lixuna** [comment]
Looks good! Thank you for updating the slide deck, @agentpoyo
